import openmc
import matplotlib.pyplot as plt

# --
# --- 3. Visualize Tracks ---
# Load the tracks file generated by the run
tracks = openmc.Tracks('tracks.h5')
print(type(tracks))
# tracks = tracks[:100]
# tracks = tracks.filter(state_filter=lambda s: s['cell_id'] in [13,23])

# Option A: Simple Matplotlib 3D Plot
# Best for a quick sanity check
ax = tracks.plot()
ax.set_title("Particle Trajectories")
plt.show()

